apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-claim
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  storageClassName: data
  resources:
    requests:
      storage: 3Gi
